name: Metamorphosis
version: '0.1.0.0'
synopsis: Transform data types using Template Haskell
author: Maxime Bourget
maintainer: bmx007@gmail.com
license: BSD3
extra-source-files:
- ChangeLog.md
dependencies:
- base >=4.8 && <5.0
- template-haskell
- containers >= 0.5 && < 0.6
library:
  source-dirs: src

tests:
  spec:
    main : "Spec.hs"
    source-dirs:
      - src
      - test

    dependencies:
      - hspec >= 2.1.8
      - doctest

